name: Deploy Blazor App to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # Adjust to your Blazor app's target version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet publish -c Release -o build_output

      - name: Debug Build Output
        run: ls -R build_output/wwwroot

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use the default GitHub token
          publish_dir: ./build_output/wwwroot  # Correct path to your build output
          force_orphan: true  # Ensures a clean commit in the gh-pages branch
