name: .NET Tests

on:
  push:
    branches:
      - '**' # Match all branches

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Specify your .NET version here

    - name: Run tests
      run: dotnet test --configuration Release --logger "trx;LogFileName=TestResult.trx"

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults.trx

    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
      with:
        name: Test Result
        path: LeagueOptimizer.Models.Tests/TestResults/TestResult.trx
        reporter: dotnet-trx
        token: ${{ github.PERSONAL_ACCESS_TOKEN}}
